title: HWP Documentation
description: HWP Documentation
theme: just-the-docs

url: https://HWP-DEV-ORG.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/HWP-DEV-ORG/just-the-docs

just_the_docs:
  navigation: # Define navigation menu
    - title: "Home"
      url: /
    - title: "guides"
      url: /guides
      children:
      - title: "Introduction"
        url: /guides/intro
      - title: "Advanced Topics"
        url: /guides/Running_on_HPC