title: HWP Documentation
description: HWP Documentation

# Use Just the Docs as a remote theme (works on GitHub Pages)
remote_theme: just-the-docs/just-the-docs

# GitHub Pages URL pieces
url: "https://hwp-dev-org.github.io"
baseurl: "/just-the-docs"

aux_links:
  "Template Repository": "https://github.com/HWP-DEV-ORG/just-the-docs"
aux_links_new_tab: true

search_enabled: true

just_the_docs:
  nav_enabled: true
