title: HWP Documentation
description: HWP Documentation
theme: just-the-docs

# GitHub Pages URL pieces
#  - url    = org/user site
#  - baseurl = repo name
url: https://HWP-DEV-ORG.github.io
baseurl: /just-the-docs

# Aux links (upper-right corner)
aux_links:
  "Template Repository":
    - "https://github.com/HWP-DEV-ORG/just-the-docs"
aux_links_new_tab: true

# Just the Docs configuration
search_enabled: true

just_the_docs:
  # enable the sidebar nav
  nav_enabled: true
